name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14 # Specify the Node.js version you want to use

    - name: Install dependencies
      run: npm install

    - name: Build and test
      run: npm run build

    - name: Create Release
      id: create_release
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag v1.0.${{ github.run_number }}
        git push --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: ./build
